# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'TestMyPodFramwork' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestMyPodFramwork
  pod 'hellosdk_xcframework_uat_dynamic_useframeworks', :path => "/Users/aaa/Documents/podLibs/MyTestLibs"
#  pod 'hellosdk_framework_uat_dynamic_useframeworks', :path => "/Users/aaa/Documents/podLibs/MyTestLibs"

  target 'TestMyPodFramworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestMyPodFramworkUITests' do
    # Pods for testing
  end

end
